[tool.poetry]
name = "fuelpricesgr"
version = "0.1.0"
description = ""
authors = ["Kostas Kokkoros <mavroprovato@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
argon2-cffi = "^21.3.0"
beautifulsoup4 = "^4.11.2"
boto3 = "^1.26.69"
fastapi = "^0.92.0"
gunicorn = "^20.1.0"
httpx = "^0.23.3"
PyPDF2 = "^3.0.1"
python-dotenv = "^0.21.1"
requests = "^2.28.2"
redis = "^4.5.1"
SQLAlchemy = "^2.0.3"
uvicorn = "^0.20.0"
sqladmin = "^0.9.0"

[tool.poetry.dev-dependencies]
coverage = "^7.1.0"
fabric = "<3.0.0"
patchwork = "^1.0.1"
pylint = "^2.16.1"
pytest = "^7.2.1"
safety = "^2.3.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
